#!/usr/bin/env python3

""" rename multiple files using your text editor. """

import glob
import os
import sys

import walkdir
import click

HEADER = """
Please change the filenames that need to be renamed and save the file.
Lines that are not changed will be ignored.

You may delete a file by putting "//" at the beginning of the line.
Note that this operation cannot be undone.

Do NOT swap the order of lines as this is what is used to match the original
filenames to the new ones.

Also, do NOT delete lines as the rename operation will be cancelled due to a
mismatch between the number of filenames before and after saving the file.

You may test the effect of the rename operation using the --dry-run parameter.

Caveats: massren expects filenames to be reasonably sane. Filenames that
include newlines or non-printable characters for example will probably not
work.
"""
HEADER = "\n".join(["// " + line for line in HEADER.splitlines()]) + "\n\n"


class FileDelete():

    def __init__(self, old):
        self.old = old

    def __repr__(self):
        return "Delete: '%s'" % self.old

    def perform(self):
        # TODO: Handle conflicts that can occur.
        # TODO: Use send2trash() instead of hard delete?
        os.remove(self.old)


class FileRename():

    def __init__(self, old, new):
        self.old = old
        self.new = new

    def __repr__(self):
        return "Rename: '%s' -> '%s'" % (self.old, self.new)

    def perform(self):
        new_dir = os.path.dirname(self.new)
        if new_dir:
            try:
                os.makedirs(new_dir)
            except FileExistsError:
                pass

        # TODO: Handle conflicts that can occur.
        os.rename(self.old, self.new)




def list_files(root, full_paths=False, only_dirs=False, only_files=False, max_depth=0):
    """ List all file in root directory. """

    walk = walkdir.filtered_walk(
        root, depth=max_depth,
        excluded_dirs=['__pycache__', '.git']
    )

    if only_dirs:
        paths = walkdir.all_dir_paths(walk)
    elif only_files:
        paths = walkdir.file_paths(walk)
    else:
        paths = walkdir.all_paths(walk)

    # Paths relative to root, rather than full paths
    relpaths = (os.path.relpath(p, root) for p in paths)

    # Sort paths by name & skip the root directory itself
    return sorted(p for p in relpaths if p != ".")

def get_files_from_editor(old_files, editor, write_header=True):
    """ Launch editor and get new file list. """

    text = "\n".join(old_files)
    if write_header:
        text = HEADER + text

    print("Waiting for file list to be saved... (Press Ctrl + C to abort) \n")

    new_text = click.edit(
        text,
        editor=editor,
        require_save=True
    )

    # No change
    if new_text is None:
        return old_files

    if write_header:
        new_text = new_text.splitlines()
        new_files = new_text[len(HEADER.splitlines()):]

    return new_files


def get_actions(root, old_files, new_files):
    """
    Perform line by line comparisons to generate a list of file actions.

    * Requires both the lists to be of the same length.
    * Deletes are represented by commenting out the files (prepending '//')
    """

    if len(old_files) != len(new_files):
        print("Number of files were changed.")
        sys.exit(1)

    for old, new in zip(old_files, new_files):
        if new.startswith("//"):
            yield FileDelete(os.path.join(root, old))
        elif old != new:
            yield FileRename(os.path.join(root, old), os.path.join(root, new))


@click.command()
@click.argument('paths', nargs=-1, type=click.Path(exists=True))
@click.option('--editor', '-e', default="code-insiders -w",
              help="Editor to use to edit files.")
@click.option('--dry-run', '-n', is_flag=True,
              help="Only show operation that will be performed.")
@click.option('--max-depth', '-d', default=0,
              help="Maximum recursion depth.")
@click.option('--only-dirs', '-D', is_flag=True,
              help="Only list directories.")
@click.option('--show-header', '-H', is_flag=True,
@click.option('--only-files', '-F', is_flag=True,
              help="Add a header in the files buffer.")
              help="Only list files.")
@click.option('--full-paths', '-f', is_flag=True,
              help="List full paths.")
@click.option('--verbose', '-v', is_flag=True,
              help="Enable verbose output.")
@click.version_option(version=0.8, prog_name="massren")
def cli(paths, editor, dry_run,
        max_depth, only_dirs, only_files, full_paths,
        hide_header, verbose):

    # No path given, use current working directory
    if not paths:
        root = "."

    # Paths is a single directory, assume we need its children
    elif len(paths) == 1 and os.path.isdir(paths[0]):
        root = paths[0]

    old_paths = list_files(root, full_paths, only_dirs, only_files, max_depth)
    new_paths = get_files_from_editor(old_paths, editor, hide_header)
    actions = list(get_actions(root, old_paths, new_paths))

    # TODO: See what conflicts can occur

    # TODO: Perform all delete operations first.

    # Execute the actions now
    for action in file_actions:

        if verbose or dry_run:
            print(action)

        if not dry_run:
            action.perform()


if __name__ == '__main__':
    cli()
